//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoPersistenceClient.TestWFServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestWFServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Operation1", ReplyAction="http://tempuri.org/IService/Operation1Response")]
        ProtoPersistenceClient.TestWFServiceReference.Operation1Response Operation1(ProtoPersistenceClient.TestWFServiceReference.Operation1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Operation1", ReplyAction="http://tempuri.org/IService/Operation1Response")]
        System.Threading.Tasks.Task<ProtoPersistenceClient.TestWFServiceReference.Operation1Response> Operation1Async(ProtoPersistenceClient.TestWFServiceReference.Operation1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation1Request {
        
        public Operation1Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation1Response {
        
        public Operation1Response() {
        }
    }
}
